"""empty message

Revision ID: 2ed0e5fd464c
Revises: 
Create Date: 2019-11-17 08:51:19.240000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed0e5fd464c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kniha', sa.Column('tema', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kniha', 'tema')
    # ### end Alembic commands ###
