"""empty message

Revision ID: 4d117dc93993
Revises: 2ed0e5fd464c
Create Date: 2019-11-17 08:55:20.406000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d117dc93993'
down_revision = '2ed0e5fd464c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kniha', sa.Column('kompozicni_vystavba', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('kontext_autorovy_tvorby', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('literarni_druh', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('literarni_kontext', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('literarni_zanr', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('motiv', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('typy_promluv', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('versova_vystavba', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('vypravec', sa.String(length=200), nullable=True))
    op.add_column('kniha', sa.Column('vypraveci_zpusoby', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kniha', 'vypraveci_zpusoby')
    op.drop_column('kniha', 'vypravec')
    op.drop_column('kniha', 'versova_vystavba')
    op.drop_column('kniha', 'typy_promluv')
    op.drop_column('kniha', 'motiv')
    op.drop_column('kniha', 'literarni_zanr')
    op.drop_column('kniha', 'literarni_kontext')
    op.drop_column('kniha', 'literarni_druh')
    op.drop_column('kniha', 'kontext_autorovy_tvorby')
    op.drop_column('kniha', 'kompozicni_vystavba')
    # ### end Alembic commands ###
